### ISSUE TITLE
Copying of features such as stalls an boulders.

### ISSUE THREAD

**Issue by Mad-phil** [goatchurchprime/tunnelvr#23]
Be good if these could be copied and pasted to facilitate easy drawing.

**Comment by goatchurchprime** [comment]
We can't have copying until we know what we are copying.  And it would violate the situation that some of the nodes are in walls and some are in free space, because they would no longer be in contact when you moved them.  The symbols should be straightforward enough that you can draw them as needed.  If we have the need for a repeated symbol, like a boulder field, then it is better to define it as a boulder field symbol (possibly filled up to a particular level) instead of printing numerous individual boulders.

Try the Menu: Normal -> Choke to see a dynamic boulder layout.

**Comment by Mad-phil** [comment]
While i understand the problem as the boulder has to be attached to the walls, there are many random boulders scattered around caves that need to be put in (not a boulder field) The current method is very cumbersome and time consuming. I think you need to think of this carefully, as this will be a big restriction.

I am looking for this to draw up a accurate 3d model of the caves, as you can see by my convential drawings, not some shambolic drawing with walls and a couple ofthings randomly put in the passage which i often see by most British cavers.
Phil
